dest: './public'

source: './source'
public: './dist'

sass:
  sourcepath: sass
  ext: '**/*.{sass,scss}'
  source: ${source}/${sass.sourcepath}/${sass.ext}
  publicpath: css
  public: ${public}/${sass.publicpath}/
  plugins:
    - autoprefixer
    - groupmedia
  help: Convert Sass to CSS

development:

production:
  production: true

environments:
  default:
    - development
  static:
    - production